// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: auth.proto

package proto

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for AuthService service

func NewAuthServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for AuthService service

type AuthService interface {
	AuthHandler(ctx context.Context, in *Token, opts ...client.CallOption) (*UserID, error)
	LoginHandler(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*Token, error)
	Registration(ctx context.Context, in *RegistrationRequest, opts ...client.CallOption) (*Token, error)
	Delete(ctx context.Context, in *UserID, opts ...client.CallOption) (*DeleteUserResponse, error)
}

type authService struct {
	c    client.Client
	name string
}

func NewAuthService(name string, c client.Client) AuthService {
	return &authService{
		c:    c,
		name: name,
	}
}

func (c *authService) AuthHandler(ctx context.Context, in *Token, opts ...client.CallOption) (*UserID, error) {
	req := c.c.NewRequest(c.name, "AuthService.AuthHandler", in)
	out := new(UserID)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) LoginHandler(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*Token, error) {
	req := c.c.NewRequest(c.name, "AuthService.LoginHandler", in)
	out := new(Token)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) Registration(ctx context.Context, in *RegistrationRequest, opts ...client.CallOption) (*Token, error) {
	req := c.c.NewRequest(c.name, "AuthService.Registration", in)
	out := new(Token)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) Delete(ctx context.Context, in *UserID, opts ...client.CallOption) (*DeleteUserResponse, error) {
	req := c.c.NewRequest(c.name, "AuthService.Delete", in)
	out := new(DeleteUserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthService service

type AuthServiceHandler interface {
	AuthHandler(context.Context, *Token, *UserID) error
	LoginHandler(context.Context, *LoginRequest, *Token) error
	Registration(context.Context, *RegistrationRequest, *Token) error
	Delete(context.Context, *UserID, *DeleteUserResponse) error
}

func RegisterAuthServiceHandler(s server.Server, hdlr AuthServiceHandler, opts ...server.HandlerOption) error {
	type authService interface {
		AuthHandler(ctx context.Context, in *Token, out *UserID) error
		LoginHandler(ctx context.Context, in *LoginRequest, out *Token) error
		Registration(ctx context.Context, in *RegistrationRequest, out *Token) error
		Delete(ctx context.Context, in *UserID, out *DeleteUserResponse) error
	}
	type AuthService struct {
		authService
	}
	h := &authServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&AuthService{h}, opts...))
}

type authServiceHandler struct {
	AuthServiceHandler
}

func (h *authServiceHandler) AuthHandler(ctx context.Context, in *Token, out *UserID) error {
	return h.AuthServiceHandler.AuthHandler(ctx, in, out)
}

func (h *authServiceHandler) LoginHandler(ctx context.Context, in *LoginRequest, out *Token) error {
	return h.AuthServiceHandler.LoginHandler(ctx, in, out)
}

func (h *authServiceHandler) Registration(ctx context.Context, in *RegistrationRequest, out *Token) error {
	return h.AuthServiceHandler.Registration(ctx, in, out)
}

func (h *authServiceHandler) Delete(ctx context.Context, in *UserID, out *DeleteUserResponse) error {
	return h.AuthServiceHandler.Delete(ctx, in, out)
}
